import type { Archetype } from "@/types/personality";

export const ARCHETYPES: Record<string, Archetype> = {
  midnight_dreamer: {
    id: "midnight_dreamer",
    title: "Midnight Dreamer",
    emoji: "🌙",
    description:
      "You exist in the liminal space between sleep and consciousness. Your playlist is a cinematic journey through rainy neon streets, late-night drives, and introspective silences. You feel music more than you hear it.",
    tagline: "Lost in the beautiful dark",
    strengths: ["Deep emotional intelligence", "Creative sensitivity", "Empathic listener", "Atmospheric taste"],
    weaknesses: ["Overthinks in silence", "Struggles with mornings", "Lives in your own world"],
    vibe: "lo-fi café at 2am",
    colors: {
      primary: "#7C3AED",
      secondary: "#1E1B4B",
      accent: "#C4B5FD",
      glow: "rgba(124, 58, 237, 0.4)",
      gradient: "linear-gradient(135deg, #1E1B4B 0%, #2D1B69 50%, #0F0A1E 100%)",
    },
    cinematicFeeling: "Like watching rain fall in slow motion under a purple street lamp",
    icon: "🌙",
    traits: ["introspective", "melancholic", "dreamy", "cinematic"],
  },
  neon_rebel: {
    id: "neon_rebel",
    title: "Neon Rebel",
    emoji: "⚡",
    description:
      "Rules are background noise to you. Your music hits hard, fast, and without apology. You live for the drop, the riff, the moment when everything cuts loose. Energy is your currency.",
    tagline: "Chaos is just energy with better lighting",
    strengths: ["Fearless intensity", "Magnetic energy", "Trend-setting instinct", "Unfiltered authenticity"],
    weaknesses: ["Restless, never satisfied", "Too much too fast", "Burns bright, burns quick"],
    vibe: "underground rave at sunrise",
    colors: {
      primary: "#F97316",
      secondary: "#1C0A00",
      accent: "#FED7AA",
      glow: "rgba(249, 115, 22, 0.4)",
      gradient: "linear-gradient(135deg, #1C0A00 0%, #431407 50%, #0A0500 100%)",
    },
    cinematicFeeling: "Neon signs reflecting off wet asphalt at 3am",
    icon: "⚡",
    traits: ["intense", "rebellious", "energetic", "raw"],
  },
  indie_philosopher: {
    id: "indie_philosopher",
    title: "Indie Philosopher",
    emoji: "🎭",
    description:
      "You find meaning in the margins. Your taste is curated, not consumed — each song chosen like a page in your personal manifesto. You see the world through a lens no algorithm could replicate.",
    tagline: "Finding truth in the B-sides of life",
    strengths: ["Intellectual curiosity", "Rare taste", "Authentic expression", "Cultural depth"],
    weaknesses: ["Dismissive of mainstream", "Overthinks everything", "Hard to impress"],
    vibe: "bookshop coffee with vinyl in the corner",
    colors: {
      primary: "#059669",
      secondary: "#022C22",
      accent: "#6EE7B7",
      glow: "rgba(5, 150, 105, 0.4)",
      gradient: "linear-gradient(135deg, #022C22 0%, #064E3B 50%, #011715 100%)",
    },
    cinematicFeeling: "A documentary film score playing while you read in the golden hour",
    icon: "🎭",
    traits: ["thoughtful", "eclectic", "indie", "intellectual"],
  },
  emotional_astronaut: {
    id: "emotional_astronaut",
    title: "Emotional Astronaut",
    emoji: "🚀",
    description:
      "You navigate feelings like an explorer mapping unknown galaxies. Your music soars — anthemic, expansive, and capable of making you cry in a grocery store. You're not afraid of feeling everything.",
    tagline: "Traveling at the speed of emotion",
    strengths: ["Boundless vulnerability", "Inspires others", "Lives fully", "Deeply empathetic"],
    weaknesses: ["Emotionally overwhelmed", "Wears heart on sleeve", "Needs time to recover"],
    vibe: "stadium concert under open sky",
    colors: {
      primary: "#0EA5E9",
      secondary: "#0C1220",
      accent: "#BAE6FD",
      glow: "rgba(14, 165, 233, 0.4)",
      gradient: "linear-gradient(135deg, #0C1220 0%, #0C4A6E 50%, #040810 100%)",
    },
    cinematicFeeling: "Rocket launch at golden hour with orchestral music swelling",
    icon: "🚀",
    traits: ["emotional", "anthemic", "expansive", "vulnerable"],
  },
  chaos_curator: {
    id: "chaos_curator",
    title: "Chaos Curator",
    emoji: "🎲",
    description:
      "Your playlist makes no sense and that's exactly the point. From jazz to hyperpop in one swipe. You don't follow trends — you create collisions. Your brain connects dots nobody else sees.",
    tagline: "Order is just unexplored chaos",
    strengths: ["Wildly creative", "Unpredictable genius", "Cross-cultural connector", "Trend destroyer"],
    weaknesses: ["Hard to follow", "Scatter-brained focus", "Alienates purists"],
    vibe: "art gallery opening meets DJ set",
    colors: {
      primary: "#EC4899",
      secondary: "#1A0010",
      accent: "#F9A8D4",
      glow: "rgba(236, 72, 153, 0.4)",
      gradient: "linear-gradient(135deg, #1A0010 0%, #831843 50%, #0D0008 100%)",
    },
    cinematicFeeling: "A Tarantino film scored by a robot having a fever dream",
    icon: "🎲",
    traits: ["chaotic", "eclectic", "unpredictable", "creative"],
  },
  vintage_romantic: {
    id: "vintage_romantic",
    title: "Vintage Romantic",
    emoji: "🌹",
    description:
      "You believe some feelings are timeless. Your music transports you — to another era, another love story, another world where things were slower and more beautiful. You have impeccable taste.",
    tagline: "Love letters written in melody",
    strengths: ["Timeless taste", "Romantic depth", "Nostalgic warmth", "Sophisticated ear"],
    weaknesses: ["Lives in the past", "Slow to adapt", "Melancholy when present fails"],
    vibe: "candlelit jazz club in Paris, 1962",
    colors: {
      primary: "#DC2626",
      secondary: "#1C0505",
      accent: "#FCA5A5",
      glow: "rgba(220, 38, 38, 0.4)",
      gradient: "linear-gradient(135deg, #1C0505 0%, #7F1D1D 50%, #0E0303 100%)",
    },
    cinematicFeeling: "Super 8 film footage of dancing in a summer garden",
    icon: "🌹",
    traits: ["nostalgic", "romantic", "warm", "timeless"],
  },
  sonic_explorer: {
    id: "sonic_explorer",
    title: "Sonic Explorer",
    emoji: "🌍",
    description:
      "Borders mean nothing to you — not genre, not language, not continent. You've probably listened to music from 40 countries this year. Your playlist is a world tour and your ears are your passport.",
    tagline: "Every sound is a new destination",
    strengths: ["Global perspective", "Open-minded mastery", "Cultural fluency", "Endless curiosity"],
    weaknesses: ["No loyal genre home", "Constantly seeking more", "Hard to pin down"],
    vibe: "rooftop in Tokyo, headphones in, world below",
    colors: {
      primary: "#D97706",
      secondary: "#1C1000",
      accent: "#FDE68A",
      glow: "rgba(217, 119, 6, 0.4)",
      gradient: "linear-gradient(135deg, #1C1000 0%, #78350F 50%, #0E0800 100%)",
    },
    cinematicFeeling: "Time-lapse of cities from above with world music swelling",
    icon: "🌍",
    traits: ["adventurous", "global", "curious", "open"],
  },
  melancholy_poet: {
    id: "melancholy_poet",
    title: "Melancholy Poet",
    emoji: "🖋️",
    description:
      "Sadness is your art form. Not despair — a beautiful, quiet, bittersweet ache that makes ordinary moments feel profound. Your music is a diary entry, a letter to the version of you that still hurts.",
    tagline: "Beauty lives in the ache",
    strengths: ["Profound emotional depth", "Artistic soul", "Authentic expression", "Healing through music"],
    weaknesses: ["Gets stuck in feeling", "Slow to move on", "Others find hard to reach"],
    vibe: "empty apartment with rain on the window",
    colors: {
      primary: "#6366F1",
      secondary: "#0F0B20",
      accent: "#A5B4FC",
      glow: "rgba(99, 102, 241, 0.4)",
      gradient: "linear-gradient(135deg, #0F0B20 0%, #312E81 50%, #06040F 100%)",
    },
    cinematicFeeling: "Black and white film in the rain, score by Max Richter",
    icon: "🖋️",
    traits: ["melancholic", "poetic", "introspective", "tender"],
  },
};

export const ARCHETYPE_LIST = Object.values(ARCHETYPES);

export const GENRE_COLORS: Record<string, string> = {
  pop: "#1DB954",
  rock: "#E53E3E",
  hip_hop: "#805AD5",
  electronic: "#00B4D8",
  indie: "#38A169",
  jazz: "#D69E2E",
  classical: "#C05621",
  rnb: "#D53F8C",
  country: "#B7791F",
  metal: "#2D3748",
  alternative: "#9F7AEA",
  folk: "#68D391",
  soul: "#F6AD55",
  reggae: "#48BB78",
  latin: "#FC8181",
  blues: "#4299E1",
  punk: "#F687B3",
  ambient: "#76E4F7",
  default: "#6366F1",
};

export const GENRE_COLOR_PALETTE = [
  "#1DB954", "#E040FB", "#00B4D8", "#FF6B6B", "#FFC107",
  "#4CAF50", "#FF5722", "#9C27B0", "#00BCD4", "#FF9800",
  "#F44336", "#3F51B5", "#009688", "#8BC34A", "#FF4081",
];
